// <auto-generated />
namespace _2013139171_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JOSEESCALANTE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JOSEESCALANTE));
        
        string IMigrationMetadata.Id
        {
            get { return "201706090000567_JOSEESCALANTE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
